### ISSUE TITLE
勇薄等 甬甫这两个部件相关的所有字有严重的错误 望新版修正感谢

### ISSUE THREAD

**Issue by jisbig5** [MY1L/Monu#2]
勇薄等 甬甫这两个部件相关的所有字有严重的错误 望新版修正感谢

**Comment by MY1L** [comment]
Monu系列有十几个字体，我不知道你说的是什么字体和什么错误（你可以截屏并直接粘贴到评论框里，gh会自动转成图片）

**Comment by jisbig5** [comment]
就是基於未來熒黑製作的字體 全部有  勇薄等 甬甫這兩個部件相關的所有字有嚴重的錯誤

**Comment by MY1L** [comment]
我在修改了。可以列出共有哪些有问题的字吗？

**Comment by jisbig5** [comment]
感謝修正 未來螢黑所有涉及 尃(旉) 勇 這三個部件的所有字都有嚴重錯誤

**Comment by MY1L** [comment]
可以列出共有哪些涉及 尃(旉) 勇 這三個部件的字吗？

**Comment by jisbig5** [comment]
㗈愑湧䞻踴 乶尃旉喸盙㗘㙛㜑愽搏溥猼縛蒪餺㬍榑煿牔禣膊賻䙏敷磗䍸䎔䗚糐縛薄賻㩤礡簙簠鎛餺䪙嚩懯璷簿髆䰊欂䥬礴䪇䶈䭦鑮斷蕭

**Comment by MY1L** [comment]
这3个字体的“斷蕭”并无问题？

**Comment by MY1L** [comment]
0.95版先发布了，看看如何。时间紧，只着重于常用字，非常用字改得不太漂亮。
